name = "AmplNLWriter"
uuid = "7c4d4715-977e-5154-bfe0-e096adeac482"
version = "1.0.1"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
Ipopt_jll = "300.1400.400"
MathOptInterface = "1.3"
julia = "1.6"

[extras]
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt_jll"]
