name = "AmplNLWriter"
uuid = "7c4d4715-977e-5154-bfe0-e096adeac482"
version = "1.2.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"

[compat]
Ipopt_jll = "=300.1400.400, =300.1400.1400, =300.1400.1600"
LinearAlgebra = "<0.0.1, 1.6"
MathOptInterface = "1.33"
OpenBLAS32_jll = "0.3.12, 0.3.24"
Test = "<0.0.1, 1.6"
Uno_jll = "1.1"
julia = "1.6"

[extras]
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Uno_jll = "396d5378-14f1-5ab1-981d-48acd51740ed"

[targets]
test = ["Ipopt_jll", "Pkg", "Test", "Uno_jll"]
