name = "AmplNLWriter"
uuid = "7c4d4715-977e-5154-bfe0-e096adeac482"
version = "0.7.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Ipopt = "0.6"
Ipopt_jll = "3.13.2"
MathOptInterface = "0.9.13"
MathProgBase = "~0.5.0, ~0.6, ~0.7"
julia = "1"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Ipopt_jll = "9cc047cb-c261-5740-88fc-0cf96f7bdcc7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt", "Ipopt_jll"]
